#!/usr/bin/env python3
"""Generate C# from the Root 33 design sheets.

Every row becomes one piece of code built from that row's columns:
  - every sheet          -> a <Sheet>Def class and one `new <Sheet>Def(...)` per row in Sheets.g.cs,
                            plus an id constant per row in Ids.g.cs
  - board_reads rows     -> members of IBoardView        (IBoardView.g.cs)
  - board_actions rows   -> members of IBoardActions     (IBoardActions.g.cs)
  - game_hooks rows      -> members of IGameHooks        (IGameHooks.g.cs)
  - state rows           -> fields of ModState           (ModState.g.cs)
  - tuning rows          -> constants of Tuning          (Tuning.g.cs)

Only columns the chosen target needs are emitted (core by default), so the core never
depends on Root's own symbols. Run the preflight first; this script refuses to
generate from sheets that fail it.

Usage: python3 -I tools/gen_cs.py [--target core|plugin] [--out src/Root33.Core/Generated]
"""
import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SHEETS_DIR = ROOT / "sheets"
TARGET_ORDER = ["core", "plugin", "release"]
HEADER = "// <auto-generated>\n// Generated by tools/gen_cs.py from sheets/*.json. Do not edit; change the sheet and regenerate.\n// </auto-generated>\n"
PREFIXES = {
    "systems": "sys.", "reskins": "reskin.", "win_conditions": "win.", "rule_tweaks": "tweak.",
    "state": "state.", "game_hooks": "hook.", "board_reads": "read.", "board_actions": "do.",
    "bot_plans": "bot.", "bot_rules": "bot.", "story_events": "story.", "spawns": "spawn.",
    "map_roles": "role.", "map_autumn": "autumn.", "overlays": "ui.", "barks": "bark.",
    "bark_triggers": "trigger.", "options": "opt.", "assets": "asset.", "tuning": "tune.",
}


def pascal(text):
    parts = [p for p in re.split(r"[^A-Za-z0-9]+", text) if p]
    out = "".join(p[:1].upper() + p[1:] for p in parts)
    if not out or out[0].isdigit():
        out = "_" + out
    return out


def class_name(sheet):
    return pascal(sheet[:-1] if sheet.endswith("s") and not sheet.endswith("ss") else sheet) + "Def"


def id_name(sheet, rid):
    pre = PREFIXES.get(sheet)
    if pre and rid.startswith(pre):
        rid = rid[len(pre):]
    return pascal(rid)


def cs_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\r", "").replace("\n", "\\n") + '"'


def cs_type(col_type):
    if col_type in ("int",):
        return "int"
    if col_type == "number":
        return "double"
    if col_type == "bool":
        return "bool"
    if col_type in ("list", "tests") or col_type.startswith("refs:"):
        return "IReadOnlyList<string>"
    if col_type == "object":
        return "IReadOnlyDictionary<string, string>"
    return "string"


def cs_value(value, col_type):
    if value is None:
        if col_type in ("list", "tests") or col_type.startswith("refs:"):
            return "Array.Empty<string>()"
        if col_type == "object":
            return "new Dictionary<string, string>()"
        if col_type == "int":
            return "0"
        if col_type == "number":
            return "0d"
        if col_type == "bool":
            return "false"
        return "null"
    if col_type == "bool":
        return "true" if value else "false"
    if col_type == "int":
        return str(int(value))
    if col_type == "number":
        return repr(float(value)) + "d"
    if col_type in ("list", "tests") or col_type.startswith("refs:"):
        if not value:
            return "Array.Empty<string>()"
        return "new[] { " + ", ".join(cs_string(v) for v in value) + " }"
    if col_type == "object":
        items = ", ".join(f"[{cs_string(str(k))}] = {cs_string(json.dumps(v) if not isinstance(v, str) else v)}" for k, v in value.items())
        return "new Dictionary<string, string> { " + items + " }"
    return cs_string(str(value))


def needed(col_spec, target):
    limit = TARGET_ORDER.index(target)
    return any(TARGET_ORDER.index(t) <= limit for t in col_spec.get("neededBy", ["core"]))


def doc(text):
    return "\n".join("        /// " + line for line in (text or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").splitlines() if line.strip()) or "        ///"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--target", choices=["core", "plugin"], default="core")
    ap.add_argument("--out", default=str(ROOT / "src" / "Root33.Core" / "Generated"))
    ap.add_argument("--skip-preflight", action="store_true")
    args = ap.parse_args()

    if not args.skip_preflight:
        pf = subprocess.run([sys.executable, "-I", str(ROOT / "tools" / "preflight.py"), "--target", args.target, "--allow-missing-tests"],
                            capture_output=True, text=True)
        if pf.returncode != 0:
            print(pf.stdout)
            print("Preflight has blocking issues; fix the sheets before generating.", file=sys.stderr)
            return 1

    schema = json.loads((SHEETS_DIR / "_schema.json").read_text(encoding="utf-8"))
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    sheets = {}
    for name, spec in schema["sheets"].items():
        doc_ = json.loads((SHEETS_DIR / spec["file"]).read_text(encoding="utf-8"))
        sheets[name] = doc_["rows"]

    # Sheets.g.cs and Ids.g.cs
    defs, tables, ids = [], [], []
    for name, spec in schema["sheets"].items():
        cols = [(c, s) for c, s in spec["columns"].items() if needed(s, args.target)]
        cname = class_name(name)
        props = "\n".join(f"{doc(s.get('description', c))}\n        public {cs_type(s['type'])} {pascal(c)} {{ get; }}" for c, s in cols)
        params = ", ".join(f"{cs_type(s['type'])} {pascal(c)[0].lower() + pascal(c)[1:]}" for c, s in cols)
        assigns = "\n".join(f"            {pascal(c)} = {pascal(c)[0].lower() + pascal(c)[1:]};" for c, s in cols)
        defs.append(f"""    /// <summary>{(spec.get('description') or name).replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')}</summary>
    public sealed partial class {cname}
    {{
{props}

        public {cname}({params})
        {{
{assigns}
        }}
    }}
""")
        rows = []
        for r in sheets[name]:
            args_ = ", ".join(cs_value(r.get(c), s["type"]) for c, s in cols)
            rows.append(f"            [{cs_string(r['id'])}] = new {cname}({args_}),")
        tables.append(f"""        public static readonly IReadOnlyDictionary<string, {cname}> {pascal(name)} = new Dictionary<string, {cname}>
        {{
{chr(10).join(rows)}
        }};
""")
        consts = "\n".join(f"            public const string {id_name(name, r['id'])} = {cs_string(r['id'])};" for r in sheets[name])
        ids.append(f"        public static class {pascal(name)}\n        {{\n{consts}\n        }}\n")

    (out / "Sheets.g.cs").write_text(HEADER + "using System;\nusing System.Collections.Generic;\n\nnamespace Root33.Core.Sheets\n{\n" + "\n".join(defs)
                                     + "\n    public static class Data\n    {\n" + "\n".join(tables) + "    }\n}\n", encoding="utf-8")
    (out / "Ids.g.cs").write_text(HEADER + "namespace Root33.Core.Sheets\n{\n    public static class Ids\n    {\n" + "\n".join(ids) + "    }\n}\n", encoding="utf-8")

    # Interfaces from board_reads, board_actions, game_hooks
    def interface(sheet, iname, sig_col, summary):
        members = []
        for r in sheets[sheet]:
            sig = r[sig_col].strip().rstrip(";")
            members.append(f"{doc(r.get('description') or r.get('when'))}\n        /// <remarks>Sheet row: {r['id']}</remarks>\n        {sig};")
        return (HEADER + "using System.Collections.Generic;\n\nnamespace Root33.Core\n{\n"
                f"    /// <summary>{summary}</summary>\n    public partial interface {iname}\n    {{\n" + "\n\n".join(members) + "\n    }\n}\n")

    (out / "IBoardView.g.cs").write_text(interface("board_reads", "IBoardView", "csSignature", "What the core reads from Root's board (one member per board_reads row)."), encoding="utf-8")
    (out / "IBoardActions.g.cs").write_text(interface("board_actions", "IBoardActions", "csSignature", "What the core changes in Root's game (one member per board_actions row)."), encoding="utf-8")
    (out / "IGameHooks.g.cs").write_text(interface("game_hooks", "IGameHooks", "csHandler", "Moments in Root's game flow the core handles (one member per game_hooks row)."), encoding="utf-8")

    # ModState from state rows
    known = {"int", "bool", "string", "ClearingId", "SeatId", "Suit", "EngineId", "PieceKind", "ItemType", "ItemState",
             "Relationship", "TurnPhase", "SpoilerMode", "Difficulty", "RemovedPiece", "BattleResult", "RoleId",
             "IReadOnlyList", "IReadOnlyCollection", "HashSet", "Dictionary", "List"}
    extra_types = set()
    fields = []
    for r in sheets["state"]:
        t = r["csType"].strip()
        for tok in re.findall(r"[A-Za-z_][A-Za-z0-9_]*", t):
            if tok not in known:
                extra_types.add(tok)
        fields.append(f"{doc(r.get('range'))}\n        /// <remarks>Sheet row: {r['id']} (owner {r['owner']}); initial: {r['initial'].replace('<', '&lt;').replace('>', '&gt;')}</remarks>\n        public {t} {id_name('state', r['id'])};")
    extra = "".join(f"    /// <summary>Declared by sheets/state.json; fields are hand-written in a partial class.</summary>\n    public sealed partial class {t} {{ }}\n\n" for t in sorted(extra_types))
    (out / "ModState.g.cs").write_text(HEADER + "using System.Collections.Generic;\n\nnamespace Root33.Core\n{\n" + extra
                                       + "    /// <summary>Mod state saved with the game (one field per state row). Initial values are set by ModState.Reset (hand-written).</summary>\n    public sealed partial class ModState\n    {\n"
                                       + "\n\n".join(fields) + "\n    }\n}\n", encoding="utf-8")

    # Tuning constants
    consts = []
    for r in sheets["tuning"]:
        v = r["value"]
        typ, lit = ("int", str(int(v))) if float(v).is_integer() else ("double", repr(float(v)) + "d")
        consts.append(f"{doc(r.get('description'))}\n        public const {typ} {id_name('tuning', r['id'])} = {lit};")
    (out / "Tuning.g.cs").write_text(HEADER + "namespace Root33.Core.Sheets\n{\n    public static class Tuning\n    {\n" + "\n\n".join(consts) + "\n    }\n}\n", encoding="utf-8")

    print(f"Generated {len(list(out.glob('*.g.cs')))} files in {out.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
